image: node:latest
variables:
  AWS_DEFAULT_REGION: eu-west-1
  APP_NAME: consensys-test-api
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm install
    - npm run lint
    - npm run build
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  dependencies:
    - build
  script:
    - npm run test:ci
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

publish:
  stage: publish
  image:
    name: docker:latest
  services:
    - docker:19-dind
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli
    - aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REGISTRY
    - aws --version
    - docker info
    - docker --version
  script:
    - docker build -t $ECR_REGISTRY:$CI_PIPELINE_IID .
    - docker push $ECR_REGISTRY:$CI_PIPELINE_IID
